### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by mattip** [yxiong/xy_python_utils#1]
Hi. If you want to let others use your code, you need to include a LICENSE file in your repo or add a COPYRIGHT header in each file. May I suggest the BSD new license, 

https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_.28.22Revised_BSD_License.22.2C_.22New_BSD_License.22.2C_or_.22Modified_BSD_License.22.29

For instance, you can see it in a github repo in numpy

https://github.com/numpy/numpy/blob/master/LICENSE.txt

**Comment by yxiong** [comment]
Just added MIT license. Thanks!
